#!/bin/sh
# postinst script for phpdocumentor
set -e

. /usr/share/debconf/confmodule

case "$1" in
    configure)
	composer-debian phpdocumentor
	chmod 777 /usr/share/phpdocumentor/phpDocumentor/var/log
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac




#DEBHELPER#

exit 0
