#!/bin/sh
# postinst script for phpdocumentor
set -e

. /usr/share/debconf/confmodule

case "$1" in
    configure)
        export COMPOSER_ALLOW_SUPERUSER=1
	export COMPOSER_HOME="/var/lib/composer/"
        export COMPOSER_NO_INTERACTION=1
	composer config -d /usr/lib/phpdocumentor --no-plugins allow-plugins.symfony/flex true || true
	composer-debian phpdocumentor
	chmod 777 /usr/share/phpdocumentor/phpDocumentor/var/log
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac




#DEBHELPER#

exit 0
